# CI for Product Catalog Service
name: product-catalog-service-ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: unit tests
        run: |
          cd src/product-catalog/
          go test -v ./...

  code-quality:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
          golangci-lint run src/product-catalog/...
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name : Build push 
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
       
  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
    - name: Update tag in kubernetes deployment manifest
      run: |
        sed -i 's/image: .*/image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}/' k8s/product-catalog/deployment.yaml
        cat k8s/product-catalog-deployment.yaml
    - name: Commit and push changes
      run: |
        git config --global user.email "neamulkabiremon@gmail.com"
        git config --global user.name "neamulkabiremon"
        git add k8s/product-catalog-deployment.yaml
        git commit -m "[CI]: Update deployment.yaml"
        git push